server:
  port: 8899

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/user_login?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai

  redis:
    port: 6379
    host: 127.0.0.1

logging:
  level:
    com.example.demo: debug


